import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Nodewave Assesment',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased h-dvh'>{children}</body>
    </html>
  );
}
